version: '3.8'  

services:
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: process.env.usernameDB;
      MONGO_INITDB_ROOT_PASSWORD: process.env.passwordDB;  

  backend:
    build:
      context: ./skalarly-backend  
    ports:
      - "3000:3000"  
    depends_on:
      - mongodb  
    

  frontend:
    build:
      context: ./skalarly-frontend  
    ports:
      - "4000:4000"  
    depends_on:
      - backend  
