language: node_js
node_js:
  - "21" # specify the Node.js version here
addons:
  chrome: stable

branches:
  only:
    - main 

cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
install:
  - npm ci
before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod
  - ng test --watch=false --browsers=ChromeHeadless
  -npm run e2e


