name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        
      - name: Log in to Heroku Container Registry
        run: heroku container:login 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 

      # Unified Application
      - name: Build and Push Unified Docker Image to Heroku
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_FS_APP_NAME }}/web ./skalarly-fs
          docker push registry.heroku.com/${{ secrets.HEROKU_FS_APP_NAME }}/web

      - name: Release Frontend Docker Image
        run: heroku container:release web --app ${{ secrets.HEROKU_FS_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

