name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 

      - name: Build and Push Backend Docker Image to Heroku
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/backend ./backend
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/backend

      - name: Build and Push Frontend Docker Image to Heroku
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/frontend ./skalarly-frontend
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/frontend

     
      - name: Release Backend Docker Image
        run: heroku container:release backend --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Frontend Docker Image
        run: heroku container:release frontend --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Additional steps for your deployment can be added here.

      - name: Configuring Git User Info
        run: |
          git config --global user.name "Olsenc07"
          git config --global user.email "skalolsen@gmail.com"
      - name: Build Angular App
        run: |
            cd skalarly-frontend
            npm install
            npm run build:prod
        
      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=skalarly-frontend/dist --no-silent --repo=https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/Olsenc07/Skalarly-FS.git
        env: 
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
