name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Backend Docker Image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/backend -f backend/Dockerfile       

      - name: Build Frontend Docker Image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/frontend -f skalarly-frontend/Dockerfile
      
      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
    
      - name: Push Backend Docker Image
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/backend

      - name: Push Frontend Docker Image
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/frontend

      - name: Release Docker Image
        run: |
          heroku container:release backend --app ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release frontend --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Angular App
        run: |
          cd skalarly-frontend  
          npm install
          npm run build:prod 

      - name: Configuring Git User Info
        run: |
          git config --global user.name "Olsenc07"
          git config --global user.email "skalolsen@gmail.com"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=skalarly-frontend/dist --no-silent --repo=https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/Olsenc07/Skalarly-FS.git
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
