name: Docker Build and Deploy

on:
  push:
    branches: 
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t skalarly-fs:${{ github.sha }} .

      - name: Run Docker Container
        run: docker run -d -p 4200:4200 skalarly-fs:${{ github.sha }} .
   
      - name: Log in to Heroku Container Registry
        run: heroku container:login 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 

      - name: Determine HEROKU_APP_NAME
        run: |
             if [[ "${{ github.ref }}" == 'refs/heads/master' ]]; then
               echo "HEROKU_APP_NAME=${{ secrets.HEROKU_FS_SKALARLY }}" >> $GITHUB_ENV
             else
               echo "HEROKU_APP_NAME=${{ secrets.HEROKU_STAGING_SKALARLY }}" >> $GITHUB_ENV
             fi
  
      - name: Tag and Push to Heroku
        run: |
            docker tag neslo:${{ github.sha }} registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
            docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
  
      - name: Release Docker Image on Heroku
        run: heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

